### PR TITLE
Modifies schema for good and not for evil

### PR DESCRIPTION
**Pull request by mikesol**
This would make interop with Wiremock more fluid:
- modifies types so that certain required fields are no longer required, as they are not in wiremock.
- makes it less lossy by having a meta field where you can throw whatever

### CODE REVIEW

**Comment by carolstran** [comment]
Somehow I'm just seeing this PR (_excellent_ name by the way). Still relevant to review @mikesol?

**Comment by mikesol** [comment]
Yes! Definitely, would be nice to add the meta field.

Mike Solomon
C.E.O., Meeshkan Machine Learning
https://www.meeshkan.com

Sent via Superhuman ( https://sprh.mn/?vip=mike@meeshkan.com )

**Review by carolstran — APPROVED** [review]
Whooooops sorry delayed but looks good to me. As far as I can tell, these aren't breaking changes for any of our other projects... but I could be wrong. If @fornwall has no objections, then I vote merge.

**Comment by carolstran** [comment]
Any objections to merging @fornwall?

**Pull request merged**
